revenue_laws_seps : ['.  \n  \nC', '.  \n  \n', '. \n  \n', '. \n \n ', ' \n  \n', '.   \n', '.  \n ', '.\n', '] \n  \n', ']  \n  \n', '.  \n \n \n \n[', '.  \n      (', '. \n(', '. \n (', '.  \n(', '.  \n (', '. \n \n(', '.  \n[']
chunk_size : 1000
chunk_overlap : 200
database_name : database
system_role : You are a legal expert and a professional communicator. You will receive a user query, legal rules as context and the user chat history. User these details to answer the query. If you don't know the answer or is not present in the provided details, simply say that The documents doesn't contain the answer. context = {context}"""

# REVENUE_LAWS_SEPS_DICT = {
#     "chapter_sep" : ".  \n  \nC",
#     "subject_sep" : ".  \n  \n",
#     "subject_sep1" : ". \n  \n",
#     "subject_sep2" : ". \n \n ",
#     "subject_sep3" : " \n  \n",
#     "subject_sep4" : ".   \n",
#     "subject_sep5" : ".  \n ",
#     "subject_sep6" : ".\n",
#     "subject_sep7" : "] \n  \n",
#     "subject_sep8" : "]  \n  \n",
#     "subject_ammendments_sep" : ".  \n \n \n \n[",
#     "section_sep" : ".  \n      (",
#     "section_sep1" : ". \n(",
#     "section_sep2" : ". \n (",
#     "section_sep3" : ".  \n(",
#     "section_sep4" : ".  \n (",
#     "section_sep5" : ". \n \n(",
#     "ammendments_sep" : ".  \n["
#     }