revenue_laws_seps : ['.  \n  \nC', '.  \n  \n', '. \n  \n', '. \n \n ', ' \n  \n', '.   \n', '.  \n ', '.\n', '] \n  \n', ']  \n  \n', '.  \n \n \n \n[', '.  \n      (', '. \n(', '. \n (', '.  \n(', '.  \n (', '. \n \n(', '.  \n[']
chunk_size : 1000
chunk_overlap : 200
database_name : "VDB-revenue_law_books"
database_path: "src/VDB-revenue_law_books"
system_role: |
  You are a legal expert and a professional communicator. Your task is to answer user queries using provided legal rules, which are given as context in the form of documents from LangChain. Follow these rules strictly:

  1. **Handling Unknowns**: If the answer is not present in the provided context:
     - Explicitly state: "The rules do not define this."
     - Provide a brief summary of the relevant context provided, if available.

  2. **Answer creating**: As the context is gonna create legal rules, so try to use the rules as is, but make sure the sentence is smooth and understandable.

  Context: {context}




# REVENUE_LAWS_SEPS_DICT = {
#     "chapter_sep" : ".  \n  \nC",
#     "subject_sep" : ".  \n  \n",
#     "subject_sep1" : ". \n  \n",
#     "subject_sep2" : ". \n \n ",
#     "subject_sep3" : " \n  \n",
#     "subject_sep4" : ".   \n",
#     "subject_sep5" : ".  \n ",
#     "subject_sep6" : ".\n",
#     "subject_sep7" : "] \n  \n",
#     "subject_sep8" : "]  \n  \n",
#     "subject_ammendments_sep" : ".  \n \n \n \n[",
#     "section_sep" : ".  \n      (",
#     "section_sep1" : ". \n(",
#     "section_sep2" : ". \n (",
#     "section_sep3" : ".  \n(",
#     "section_sep4" : ".  \n (",
#     "section_sep5" : ". \n \n(",
#     "ammendments_sep" : ".  \n["
#     }